# Generated by Django 5.2.5 on 2025-09-14 13:08

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('CV', 'CV'), ('ATTESTATION', 'Attestation'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50)),
                ('fichier', models.FileField(upload_to='documents/', validators=[documents.models.validate_file_size, documents.models.validate_extension])),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('visible_par_manager', models.BooleanField(default=False)),
                ('valide_par_rh', models.BooleanField(default=False)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
